# Generated by Django 3.0.3 on 2020-03-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('B', 'boys'), ('G', 'girls')], max_length=1)),
                ('price', models.FloatField()),
                ('slug', models.SlugField()),
                ('description', models.TextField(default='This is my description')),
            ],
        ),
    ]
