# Generated by Django 3.0.3 on 2020-03-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images.jpg', upload_to=''),
        ),
    ]
